:search: lolcats
:user_ids: 12345392,235535245
:twitter:
  :consumer_key: xxxxxxxxxx
  :consumer_secret: xxxxxxxxxxxxx
  :access_key: xxxxxxxxxxx
  :access_secret: xxxxxxxxxxxxxxx
:hipchat:
  :api_token: xxxxx
  :room: Main
